In [12]:
import numpy as np

1- Sıfırlardan oluşan 3x3 şeklinde bir numpy dizisi yaratın.

In [13]:
array1 = np.zeros((3,3))

In [14]:
array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2- Bir dizi içerisindeki tüm tek sayıları seçin ve ayrıştırın.

İpucu:

Girdi: array[0,1,2,3,4,5,6,7] ve istenen çıktı: array[1,3,5,7]

In [29]:
x = np.array([0,1,2,3,4,5,6,7])
y = np.array([])
for i in x:
    if i % 2 == 1:
        y = np.append(y,i)

In [30]:
y

array([1., 3., 5., 7.])

3- 1 boyutlu bir diziyi 2 satırlı 2 boyutlu bir diziye dönüştürün.

İpucu:
Girdi: array[0,1,2,3,4,5,6,7]
İstenen çıktı: array([[0, 1, 2, 3],[4, 5, 6, 7]])

In [32]:
array3 =  np.array([0,1,2,3,4,5,6,7])
convert_array = np.reshape(array3,(2,4))

In [33]:
convert_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

4- birinci_dizi ve ikinci_dizi dizilerini dikey olarak birleştirin (stack).

birinci_dizi = np.arange(10).reshape(2,-1)
ikinci_dizi = np.repeat(1, 10).reshape(2,-1)

In [80]:
birinci_dizi = np.arange(10)
print(birinci_dizi)
print(birinci_dizi.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [81]:
birinci_dizi = birinci_dizi.reshape(2,-1)
print(birinci_dizi)
print(birinci_dizi.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [82]:
ikinci_dizi = np.repeat(1, 10)
print(ikinci_dizi)
print(ikinci_dizi.shape)

[1 1 1 1 1 1 1 1 1 1]
(10,)


In [83]:
ikinci_dizi = ikinci_dizi.reshape(2,-1)
print(ikinci_dizi)
print(ikinci_dizi.shape)

[[1 1 1 1 1]
 [1 1 1 1 1]]
(2, 5)


In [84]:
yığın = np.append(birinci_dizi, ikinci_dizi)
print(yığın)
print(yığın.shape)

[0 1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1]
(20,)


In [85]:
yığın = np.reshape(yığın,(4,-1))
print(yığın)
print(yığın.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(4, 5)


5- a dizisinden 5'ten büyük ve 10'dan küçük olan elemanları alın.

a = np.arange(0,15,2)

In [37]:
a = np.arange(0,15,2)
empty_a = np.array([])
for i in a:
    if i > 5 and i < 10:
        empty_a = np.append(empty_a,i)

In [38]:
empty_a

array([6., 8.])

6- a dizisinin ortalamasını (mean), medyanını (median) ve standart sapmasını (standard deviation) bulun.

In [41]:
a = np.arange(0,15,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [43]:
np.mean(a)

7.0

In [44]:
np.median(a)

7.0

In [45]:
np.std(a)

4.58257569495584

7- a dizisindeki 0.5’ten büyük elemanların indekslerini bulun.
Bu indeksleri idx adlı yeni bir değişkende tanımlayın.

a = np.random.rand(1000)

In [86]:
a = np.random.random(1000)
idx = np.array([])

for i in range(len(a)):
    ele = a[i]
    if ele > 0.5:
        idx = np.append(idx,i)

print(len(idx))

499


8- Bir vektörü ters çevirin (ilk eleman son eleman olur).

In [54]:
a = np.arange(0,15,2)
reverse_a = np.flip(a)
reverse_a

array([14, 12, 10,  8,  6,  4,  2,  0])

9- Boyutu 10 olan rastgele bir vektör oluşturun ve en büyük değerin önüne 0 değerini ekleyin.

In [55]:
vektör = np.random.rand(10)
print(vektör)

[0.93289113 0.39198796 0.39905371 0.7508026  0.77372118 0.18672471
 0.66549031 0.02288725 0.40269582 0.28518711]


In [56]:
print(np.argmax(vektör))

0


In [57]:
vektör_rev = np.insert(vektör, np.argmax(vektör), 0)
print(vektör_rev)

[0.         0.93289113 0.39198796 0.39905371 0.7508026  0.77372118
 0.18672471 0.66549031 0.02288725 0.40269582 0.28518711]


10- Bir matrisin her satırından o satırın kendi ortalamasını çıkarın.

In [58]:
x = np.reshape(vektör,(2,5))
print(x)

[[0.93289113 0.39198796 0.39905371 0.7508026  0.77372118]
 [0.18672471 0.66549031 0.02288725 0.40269582 0.28518711]]


In [59]:
mean = np.mean(x) # mean fonksiyonun ikinci argümanı için, axis = 1 satırlar, axis = 0 sütunlar
print(mean)

satır_ortalama = np.mean(x, axis=1)
print(satır_ortalama)

0.4811441773312559
[0.64969132 0.31259704]


In [60]:
sütun_ortalama = np.mean(x, axis = 0)
print(sütun_ortalama)

[0.55980792 0.52873914 0.21097048 0.57674921 0.52945414]


In [61]:
satır_ortalama = np.mean(x, axis = 1)
satır_ortalama

array([0.64969132, 0.31259704])

In [62]:
np.repeat(satır_ortalama, 5).shape

(10,)

In [63]:
satır_ortalama_dizisi = np.repeat(satır_ortalama, 5).reshape(2,5)
satır_ortalama_dizisi

array([[0.64969132, 0.64969132, 0.64969132, 0.64969132, 0.64969132],
       [0.31259704, 0.31259704, 0.31259704, 0.31259704, 0.31259704]])

In [64]:
final = x - satır_ortalama_dizisi
print(final)

[[ 0.28319982 -0.25770336 -0.25063761  0.10111128  0.12402986]
 [-0.12587233  0.35289327 -0.28970979  0.09009878 -0.02740993]]


Repeat fonksiyonu nasıl çalışır?

In [65]:
print(np.repeat(3, 4))              # 3'ü 4 kez tekrarlar

x = np.array([[1,2],[3,4]])         # 2x2 matris
print(x)                            # matrisi yazdırır

print(np.repeat(x, 2))              # tüm elemanları (düzleştirip) 2 kez tekrarlar
print(np.repeat(x, 3, axis=0))      # satırları 3 kez tekrarlar
print(np.repeat(x, 3, axis=1))      # sütunları 3 kez tekrarlar
print(np.repeat(x, [1, 2], axis=0)) # 1. satır 1 kez, 2. satır 2 kez tekrar

[3 3 3 3]
[[1 2]
 [3 4]]
[1 1 2 2 3 3 4 4]
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
[[1 2]
 [3 4]
 [3 4]]


11- worldometers.info sitesine göre, 17 Şubat 2019 saat 11:00’de dünya nüfusu yaklaşık 7.684.621.550 ve günlük ortalama büyüme hızı yaklaşık 107.000’dir.

### Dünya nüfusu
dünya_pop = 7684621550
### Günlük ortalama büyüme hızı
büyüme_hızı = 107000


17 Şubat’tan 26 Şubat’a kadar dünya nüfusunu gösteren bir dizi (dünya_pop_dizisi) oluşturun. Daha sonra bu bilgileri içeren bir sözlük (dictionary) oluşturun ve numpy.save kullanarak dosyaya kaydedin.

In [69]:
world_pop = 7684621550
growth_rate = 107000
world_pop_array = np.arange(world_pop,world_pop+(10*growth_rate),growth_rate)

In [70]:
world_pop_array

array([7684621550, 7684728550, 7684835550, 7684942550, 7685049550,
       7685156550, 7685263550, 7685370550, 7685477550, 7685584550],
      dtype=int64)

In [72]:
day_array = np.array(["17 Şubat", "18 Şubat", "19 Şubat", "20 Şubat", "21 Şubat", "22 Şubat", "23 Şubat", "24 Şubat", "25 Şubat", "26 Şubat",])

In [75]:
world_pop_dict = dict(zip(day_array, world_pop_array))

In [76]:
world_pop_dict

{'17 Şubat': 7684621550,
 '18 Şubat': 7684728550,
 '19 Şubat': 7684835550,
 '20 Şubat': 7684942550,
 '21 Şubat': 7685049550,
 '22 Şubat': 7685156550,
 '23 Şubat': 7685263550,
 '24 Şubat': 7685370550,
 '25 Şubat': 7685477550,
 '26 Şubat': 7685584550}

Not: zip() fonksiyonu, her bir verilen iteratörün ilk elemanlarını birleştiren, sonra ikinci elemanları birleştiren vb. şekilde, demetler (tuple) halinde dönen bir iteratör (iterator) objesi oluşturur.

In [77]:
np.save("example_dictionary.npy", world_pop_dict)

12- Belirli bir dizi (dizi) ve istediğiniz bir adım (veya pencere boyutu) için bir time_resolved fonksiyonu yazın.

Fonksiyon şu üç parametreyi alacak:
time_resolved(dizi, pencere_genişliği, kayma)

Örnek olarak,
dizi = np.array([1, 2, 6, 4, 5, 4, 2, 7, 8, 9]) için
time_resolved(dizi, 3, 4) çağrıldığında, fonksiyonun çıktısı [4, 5, 4] olmalıdır.

In [78]:
def time_resolved(dizi,pencere_genişliği,kayma):
    alt_dizi=np.array([])
    for i in range(kayma-1,kayma+pencere_genişliği-1):
        alt_dizi=np.append(alt_dizi,dizi[i])
    return alt_dizi

In [79]:
dizi = np.array([1, 2, 6, 4, 5, 4, 2, 7, 8, 9])
time_resolved(dizi, 3, 4)

array([4., 5., 4.])